(function(){
'use strict';
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function safeUrl(v,image=false){const u=String(v||'').trim();if(!u||/[\u0000-\u001f\u007f]/.test(u))return '';if(image&&/^data:image\/(png|jpeg|webp|gif);base64,[A-Za-z0-9+/=]+$/.test(u))return u;if(/^https?:\/\//i.test(u)){try{return new URL(u).hostname?u:'';}catch{return '';}}if(!image&&/^mailto:[^\s<>]+$/i.test(u))return u;if(/^assets\/[a-zA-Z0-9_./% -]+$/.test(u)&&!u.includes('..'))return u;return '';}
const link=(u,t,cl='')=>safeUrl(u)?`<a class="${e(cl)}" href="${e(safeUrl(u))}"${/^https?:/i.test(u)?' target="_blank" rel="noopener noreferrer"':''}>${e(t)}</a>`:'';
const img=(u,alt,cl='')=>safeUrl(u,true)?`<img class="${cl}" src="${e(safeUrl(u,true))}" alt="${e(alt)}" loading="lazy" decoding="async">`:'';
const para=t=>String(t||'').split(/\n\s*\n/).filter(Boolean).map(p=>`<p>${e(p).replace(/\n/g,'<br>')}</p>`).join('');
const chips=t=>String(t||'').split(',').map(t=>t.trim()).filter(Boolean).map(t=>`<span>${e(t)}</span>`).join('');
const edit=(key,label='Edit content',add=false)=>`<a class="edit-action owner-only" href="editor.html?section=${key}${add?'&action=add':''}">${add?'+ ':''}${e(label)}</a>`;
function galleryHTML(data){const photos=data.gallery.filter(x=>safeUrl(x.image,true));if(!photos.length)return `<div class="gallery-empty"><span class="empty-label">RESEARCH / CONFERENCES / MILESTONES</span><h3>A visual record of the journey.</h3><p>Photographs will appear here as the collection grows.</p>${edit('gallery','Add photographs',true)}</div>`;
return `<div class="gallery" role="region" aria-roledescription="carousel" aria-label="Research and milestones photographs" tabindex="0"><div class="gallery-viewport"><div class="gallery-track">${photos.map((x,i)=>`<figure class="gallery-slide" role="group" aria-roledescription="slide" aria-label="${i+1} of ${photos.length}"${i?' aria-hidden="true" inert':''}><button class="gallery-image-button" type="button" data-gallery-open="${i}" aria-label="Enlarge ${e(x.title||'photograph')}">${img(x.image,x.imageAlt||x.title)}</button><figcaption><strong>${e(x.title)}</strong><span>${e(x.detail)}</span></figcaption></figure>`).join('')}</div></div><div class="gallery-progress" aria-hidden="true"><span></span></div><div class="gallery-controls"><div class="gallery-position"><strong id="gallery-position">01</strong><span> / ${String(photos.length).padStart(2,'0')}</span></div><div class="gallery-indication">${photos.length>1?'<span id="gallery-auto-status">Slideshow</span><span class="swipe-hint">Swipe or use arrows</span>':'Full image · click to enlarge'}</div><div class="gallery-buttons"><button id="gallery-prev" type="button" aria-label="Previous photograph"${photos.length<2?' disabled':''}>←</button>${photos.length>1?'<button id="gallery-play" type="button" aria-label="Pause slideshow">Pause</button>':''}<button id="gallery-next" type="button" aria-label="Next photograph"${photos.length<2?' disabled':''}>→</button></div></div>${photos.length>1?`<div class="gallery-thumbnails" aria-label="Choose photograph">${photos.map((x,i)=>`<button type="button" data-gallery-go="${i}" aria-label="Show photograph ${i+1}: ${e(x.title)}" aria-current="${i===0?'true':'false'}">${img(x.image,x.imageAlt||x.title)}</button>`).join('')}</div>`:''}<span class="sr-only" id="gallery-announcement" aria-live="polite"></span></div>`;}
function build(d){const p=d.profile;const published=d.publications.filter(x=>x.status==='Published'),pending=d.publications.filter(x=>x.status!=='Published');const nav=[['about','Research'],['publications','Publications'],['projects','Projects'],['experience','Experience'],['education','Credentials']];if(d.settings.showGallery)nav.push(['gallery','Gallery']);nav.push(['contact','Contact']);
const header=`<div class="header-inner"><a class="brand" href="#about"><span class="brand-mark">${e(p.initials)}</span><span>${e(p.shortName)}<small>RESEARCH PORTFOLIO</small></span></a><button id="menu-toggle" aria-controls="navigation" aria-expanded="false" type="button">Menu <span aria-hidden="true">☰</span></button><nav id="navigation" aria-label="Main navigation">${nav.map(([id,t])=>`<a href="#${id}">${t}</a>`).join('')}</nav></div>`;
const section=(id,n,title,subtitle,content,key=id,label='Add entry')=>`<section class="section" id="${id}" aria-labelledby="heading-${id}"><div class="section-heading"><div class="section-label"><span>${n}</span><span>${e(subtitle)}</span></div><div class="heading-row"><h2 id="heading-${id}">${title}</h2><div class="section-actions">${edit(key,label,true)}${edit(key,'Edit section')}</div></div></div>${content}</section>`;
const pub=x=>`<article class="publication"><div class="pub-index"><span>${e(x.year)}</span><span class="pub-type">${e(x.type)}</span></div><div class="pub-main"><div class="pub-meta"><span class="badge ${x.status==='Published'?'':'pending'}">${e(x.status)}</span><span>${e(x.venue)}</span></div><h3>${e(x.title)}</h3><p class="authors">${e(x.authors).split(e(p.name)).join(`<strong>${e(p.name)}</strong>`)}</p>${link(x.url,'Read publication ↗','text-link')}</div></article>`;
const time=(x,education=false)=>`<article class="timeline-item"><div class="period">${e(x.period)}</div><div class="timeline-main"><h3>${e(x.title)}</h3><p class="organization">${e(education?x.institution:x.organization)}</p>${x.location?`<p class="location">${e(x.location)}</p>`:''}${x.detail?`<p class="detail">${e(x.detail)}</p>`:''}${x.description?`<p class="description">${e(x.description)}</p>`:''}</div></article>`;
return {header,body:`
<section class="hero" id="about" aria-labelledby="hero-title"><div class="hero-grid" aria-hidden="true"></div><div class="hero-inner ${safeUrl(p.portrait,true)?'with-portrait':''}"><div class="hero-copy"><p class="eyebrow">${e(p.focusLine||'Artificial intelligence · Intelligent systems · Engineering')}</p><h1 id="hero-title">${e(p.name)}</h1><p class="hero-role">${e(p.role)}</p><h2 class="hero-statement">${e(p.headline)}</h2><p class="hero-intro">${e(p.intro)}</p><div class="hero-actions">${link('mailto:'+p.email,'Let’s connect ↗','button primary')}${link(p.cv,'Download CV ↓','button ghost')}<a class="hero-work" href="#projects">Explore my work <span aria-hidden="true">↓</span></a></div><div class="hero-social">${link(p.scholar,'Google Scholar')}${link(p.linkedin,'LinkedIn')}${link(p.github,'GitHub')}</div>${edit('profile','Edit introduction')}</div>${safeUrl(p.portrait,true)?`<div class="hero-portrait">${img(p.portrait,p.portraitAlt)}<span>${e(p.affiliation)}</span></div>`:''}</div><div class="hero-bottom"><span>Based in ${e(p.location)}</span><span>${e(p.affiliation)}</span><a href="#research">Research direction <span aria-hidden="true">↓</span></a></div></section>
<div class="content-shell"><section class="section research-section" id="research" aria-labelledby="heading-research"><div class="section-heading"><div class="section-label"><span>01</span><span>Research direction</span></div><div class="heading-row"><h2 id="heading-research">Curiosity. Rigor. Application.</h2><div class="section-actions">${edit('profile','Edit biography')}${edit('interests','Add research interest',true)}</div></div></div><div class="research-body"><div class="bio">${para(p.about)}</div><p class="opportunity"><span>Looking ahead</span>${e(p.opportunity)}</p></div><div class="interests">${d.interests.map((x,i)=>`<article class="interest"><span class="interest-index">R / ${String(i+1).padStart(2,'0')}</span><h3>${e(x.title)}</h3><p>${e(x.description)}</p></article>`).join('')}</div><div class="owner-only secondary-editor">${edit('interests','Edit research interests')}</div></section>
${section('publications','02','Publications','Peer-reviewed work & ongoing research',`<div class="section-intro"><p>Published research and manuscripts in progress, with publication status shown for each work.</p>${link(p.scholar,'View Google Scholar ↗','text-link')}</div><div class="publications">${published.map(pub).join('')}</div>${pending.length?`<div class="subsection-title"><h3>Manuscripts in progress</h3><span>${pending.length} works</span></div>${pending.map(pub).join('')}`:''}`,'publications','Add paper')}
${section('projects','03','Selected projects','From research questions to working systems',`<div class="project-grid">${d.projects.map((x,i)=>`<article class="project">${img(x.image,x.imageAlt||x.title,'project-image')}<div class="project-body"><div class="project-top"><span>${e(x.category)}</span><span class="project-number">${String(i+1).padStart(2,'0')}</span></div><h3>${e(x.title)}</h3><p>${e(x.summary)}</p><div class="project-contribution"><span>Contribution</span><p>${e(x.contribution)}</p></div><div class="tags">${chips(x.tags)}</div>${[x.postUrl,x.codeUrl,x.demoUrl].some(u=>safeUrl(u))?`<div class="project-links">${link(x.postUrl,'Project story ↗')}${link(x.codeUrl,'Code ↗')}${link(x.demoUrl,'Live demo ↗')}</div>`:''}</div></article>`).join('')}</div>`,'projects','Add project')}
${section('experience','04','Research & experience','Where I contribute',d.experience.map(x=>time(x)).join(''),'experience','Add experience')}
${section('education','05','Education & expertise','Engineering foundations',d.education.map(x=>time(x,true)).join('')+`<div class="subsection-title"><h3>Technical expertise</h3><div class="section-actions">${edit('skills','Add skill group',true)}${edit('skills','Edit skills')}</div></div><div class="skills-grid">${d.skills.map(x=>`<article><h4>${e(x.title)}</h4><p>${e(x.items)}</p></article>`).join('')}</div>`,'education','Add education')}
${section('awards','06','Honors & recognition','Milestones earned',`<div class="awards-grid">${d.awards.map(x=>`<article class="award"><span class="award-symbol" aria-hidden="true">✧</span><div><h3>${e(x.title)}</h3><p>${e(x.organization)}${x.year?' · '+e(x.year):''}</p>${x.detail?`<p class="detail">${e(x.detail)}</p>`:''}</div></article>`).join('')}</div>`,'awards','Add award')}
${section('certifications','07','Training & certifications','Continuing to learn',`<div class="cert-grid">${d.certifications.map((x,i)=>`<article class="cert"><div class="cert-date">${e(x.date)}</div><h3>${e(x.title)}</h3><p class="organization">${e(x.issuer)}</p><p>${e(x.detail)}</p><div class="cert-actions">${link(x.url,'View credential ↗','text-link')}${safeUrl(x.image,true)?`<button class="text-link" data-certificate="${i}" type="button">View certificate ↗</button>`:''}</div></article>`).join('')}</div>`,'certifications','Add certificate')}
${section('service','08','Leadership & engagement','Research as a shared effort',d.service.map(x=>time(x)).join('')+`<div class="subsection-title"><h3>Presentations</h3><div class="section-actions">${edit('presentations','Add presentation',true)}${edit('presentations','Edit presentations')}</div></div>${d.presentations.map(x=>`<article class="presentation"><h4>${e(x.title)}</h4><p>${e(x.venue)}<br>${e(x.detail)}</p></article>`).join('')}`,'service','Add role')}
${d.settings.showGallery?section('gallery','09','Beyond the desk','Conferences, research & milestones',galleryHTML(d),'gallery','Add photographs'):''}
</div><section class="contact-section" id="contact" aria-labelledby="contact-heading"><div class="contact-inner"><div><p class="eyebrow">A shared question is a good beginning.</p><h2 id="contact-heading">Let’s explore<br>what comes next.</h2></div><div class="contact-detail"><p>${e(p.opportunity)}</p>${link('mailto:'+p.email,p.email,'contact-email')}<div class="contact-links">${link(p.scholar,'Scholar ↗')}${link(p.linkedin,'LinkedIn ↗')}${link(p.github,'GitHub ↗')}${link(p.cv,'CV ↓')}</div>${edit('profile','Edit contact details')}</div></div></section>
<footer class="site-footer"><div><span>© ${new Date().getFullYear()} ${e(p.shortName)}</span><span>Updated ${e(p.updated)}</span></div><div class="footer-tools">${d.settings.showCounter?'<span class="visit-counter" title="Total page visits, including repeat visits"><span class="counter-label">Site visits</span><strong id="visit-total" aria-live="polite">—</strong></span>':''}<button id="manage-toggle" type="button">Manage content</button><a href="#about">Back to top ↑</a></div></footer>`};}
if(typeof module!=='undefined'&&module.exports)module.exports={build,safeUrl,escape:e,galleryHTML};
if(typeof document==='undefined')return;
const query=new URLSearchParams(location.search),preview=query.get('preview')==='1';
let owner=!preview&&(location.protocol==='file:'||query.get('manage')==='1');try{if(!preview&&sessionStorage.getItem('portfolio-owner')==='1')owner=true;}catch{}
let current,sectionObserver,galleryCleanup=()=>{},galleryController=null,countResult=null,counterStarted=false;
function applyOwner(){document.body.classList.toggle('editing',owner);document.getElementById('manage-bar').hidden=!owner;const b=document.getElementById('manage-toggle');if(b)b.textContent=owner?'Exit editing mode':'Manage content';}
function render(d){current=d;galleryCleanup();const html=build(d);document.getElementById('site-header').innerHTML=html.header;document.getElementById('page').innerHTML=html.body;document.title=d.profile.name+' | AI & Intelligent Systems Research';applyOwner();if(sectionObserver)sectionObserver.disconnect();if('IntersectionObserver'in window){sectionObserver=new IntersectionObserver(entries=>{entries.forEach(x=>{if(x.isIntersecting)document.querySelectorAll('#navigation a').forEach(a=>{const on=a.hash==='#'+x.target.id;a.classList.toggle('active',on);if(on)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});});},{rootMargin:'-18% 0px -60% 0px'});document.querySelectorAll('main section[id]').forEach(x=>sectionObserver.observe(x));}setupGallery();updateCounter();}
function setupGallery(){const root=document.querySelector('.gallery');galleryController=null;if(!root)return;const photos=current.gallery.filter(x=>safeUrl(x.image,true));const track=root.querySelector('.gallery-track'),slides=[...root.querySelectorAll('.gallery-slide')],thumbs=[...root.querySelectorAll('[data-gallery-go]')],progress=root.querySelector('.gallery-progress span');let index=0,timer=null,visible=false,hover=false,focus=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let playing=!!current.settings.galleryAutoplay&&!reduced&&photos.length>1;const delay=Math.max(4,Math.min(20,Number(current.settings.galleryInterval)||6))*1000;
function stopTimer(){clearTimeout(timer);timer=null;progress.style.transition='none';progress.style.width='0%';}
function schedule(){stopTimer();const status=root.querySelector('#gallery-auto-status'),play=root.querySelector('#gallery-play');if(play){play.textContent=playing?'Pause':'Play';play.setAttribute('aria-label',playing?'Pause slideshow':'Start slideshow');}const paused=!playing||hover||focus||!visible||document.hidden;root.classList.toggle('auto-running',!paused);if(status)status.textContent=playing?(paused?'Auto-advance paused':`Auto-advance · ${delay/1000}s`):'Manual browsing';if(!paused&&photos.length>1){void progress.offsetWidth;progress.style.transition=`width ${delay}ms linear`;progress.style.width='100%';timer=setTimeout(()=>go(index+1,false),delay);}}
function go(next,manual=true){index=(next+photos.length)%photos.length;track.style.transform=`translateX(-${index*100}%)`;slides.forEach((s,i)=>{s.inert=i!==index;s.setAttribute('aria-hidden',String(i!==index));});thumbs.forEach((t,i)=>t.setAttribute('aria-current',String(i===index)));root.querySelector('#gallery-position').textContent=String(index+1).padStart(2,'0');if(manual){playing=false;root.querySelector('#gallery-announcement').textContent=`Photograph ${index+1} of ${photos.length}: ${photos[index].title}`;}schedule();}
root.querySelector('#gallery-prev').onclick=()=>go(index-1);root.querySelector('#gallery-next').onclick=()=>go(index+1);const play=root.querySelector('#gallery-play');if(play)play.onclick=()=>{playing=!playing;focus=false;schedule();};thumbs.forEach(t=>t.onclick=()=>go(Number(t.dataset.galleryGo)));root.onkeydown=ev=>{if(ev.key==='ArrowLeft'||ev.key==='ArrowRight'){ev.preventDefault();go(index+(ev.key==='ArrowRight'?1:-1));}};root.onpointerenter=ev=>{if(ev.pointerType==='mouse'){hover=true;schedule();}};root.onpointerleave=()=>{hover=false;schedule();};root.onfocusin=ev=>{if(ev.target!==play){focus=true;schedule();}};root.onfocusout=ev=>{if(!root.contains(ev.relatedTarget)){focus=false;schedule();}};let touchX=0,touchY=0;root.addEventListener('touchstart',ev=>{touchX=ev.changedTouches[0].clientX;touchY=ev.changedTouches[0].clientY;},{passive:true});root.addEventListener('touchend',ev=>{const dx=ev.changedTouches[0].clientX-touchX,dy=ev.changedTouches[0].clientY-touchY;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy))go(index+(dx<0?1:-1));},{passive:true});const observe=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;schedule();},{threshold:.25});observe.observe(root);const visibility=()=>schedule();document.addEventListener('visibilitychange',visibility);galleryCleanup=()=>{stopTimer();observe.disconnect();document.removeEventListener('visibilitychange',visibility);};galleryController={go,photos,get index(){return index;},pause(){playing=false;schedule();}};go(0,false);}
let modalPhotos=[],modalIndex=0;
const modal=document.getElementById('lightbox');function showModalImage(){const p=modalPhotos[modalIndex];const im=document.getElementById('lightbox-image');im.src=safeUrl(p.image,true);im.alt=p.imageAlt||p.title;document.getElementById('lightbox-caption').textContent=[p.title,p.detail].filter(Boolean).join(' · ');document.getElementById('lightbox-position').textContent=`${modalIndex+1} / ${modalPhotos.length}`;document.getElementById('lightbox-prev').hidden=document.getElementById('lightbox-next').hidden=modalPhotos.length<2;}
function openModal(photos,index){modalPhotos=photos;modalIndex=index;galleryController?.pause();showModalImage();modal.showModal();}function moveModal(n){modalIndex=(modalIndex+n+modalPhotos.length)%modalPhotos.length;showModalImage();}
document.getElementById('lightbox-close').onclick=()=>modal.close();document.getElementById('lightbox-prev').onclick=()=>moveModal(-1);document.getElementById('lightbox-next').onclick=()=>moveModal(1);modal.addEventListener('keydown',ev=>{if(ev.key==='ArrowLeft'||ev.key==='ArrowRight'){ev.preventDefault();moveModal(ev.key==='ArrowRight'?1:-1);}});
function closeMenu(){document.getElementById('navigation')?.classList.remove('open');document.getElementById('menu-toggle')?.setAttribute('aria-expanded','false');}
document.addEventListener('click',ev=>{const menu=ev.target.closest('#menu-toggle');if(menu){const open=document.getElementById('navigation').classList.toggle('open');menu.setAttribute('aria-expanded',String(open));}else if(ev.target.closest('#navigation a')||!ev.target.closest('#site-header'))closeMenu();if(ev.target.closest('#manage-toggle,#exit-manage')){owner=!owner;try{sessionStorage.setItem('portfolio-owner',owner?'1':'0');}catch{}applyOwner();updateCounter();}const g=ev.target.closest('[data-gallery-open]');if(g&&galleryController)openModal(galleryController.photos,+g.dataset.galleryOpen);const c=ev.target.closest('[data-certificate]');if(c)openModal([current.certifications[+c.dataset.certificate]],0);});document.addEventListener('keydown',ev=>{if(ev.key==='Escape'){closeMenu();}});
function updateCounter(){const el=document.getElementById('visit-total');if(!el)return;if(countResult!==null){el.textContent=Number(countResult).toLocaleString();return;}if(!current.settings.counterEndpoint){el.textContent='—';el.parentElement.title=owner?'Connect the visit counter under Editor → Display settings.':'Visit counting is not connected yet.';return;}if(preview||owner||!/^https?:$/.test(location.protocol)||['localhost','127.0.0.1','terminal.local'].includes(location.hostname)){el.textContent='Preview';el.parentElement.title='Local previews and editing mode do not add visits.';return;}if(counterStarted)return;let endpoint;try{endpoint=new URL(current.settings.counterEndpoint);if(endpoint.protocol!=='https:'||endpoint.username||endpoint.password)throw new Error();}catch{el.textContent='Unavailable';return;}counterStarted=true;const abort=new AbortController();const timeout=setTimeout(()=>abort.abort(),7000);fetch(endpoint.href,{method:'POST',mode:'cors',credentials:'omit',cache:'no-store',referrerPolicy:'no-referrer',signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('Counter unavailable');return r.json();}).then(result=>{if(!Number.isSafeInteger(result.count)||result.count<0)throw new Error('Invalid count');countResult=result.count;const label=document.getElementById('visit-total');if(label)label.textContent=result.count.toLocaleString();}).catch(()=>{const label=document.getElementById('visit-total');if(label){label.textContent='Unavailable';label.parentElement.title='The visit service could not be reached. No local or estimated total is shown.';}}).finally(()=>clearTimeout(timeout));}
if(window.PORTFOLIO_DATA)render(window.PORTFOLIO_DATA);window.addEventListener('pageshow',event=>{if(event.persisted){counterStarted=false;countResult=null;updateCounter();}});
if(preview&&window.parent!==window)window.addEventListener('message',event=>{if(event.source===window.parent&&event.data?.type==='portfolio-preview'){try{render(event.data.data);}catch{}}});
})();
